### ISSUE TITLE
TypeError: can't concat str to bytes

### ISSUE THREAD

**Issue by jmaumene** [atpage/chirp#3]
`ERROR: -- Exception: --
ERROR: Traceback (most recent call last):
  File "/home/julien/Applications/chirp/chirp/drivers/uv5r.py", line 819, in sync_in
    self._mmap = _do_download(self)
  File "/home/julien/Applications/chirp/chirp/drivers/uv5r.py", line 590, in _do_download
    data += radio.MODEL.ljust(8)
TypeError: can't concat str to bytes
`

```
--- a/chirp/drivers/uv5r.py
+++ b/chirp/drivers/uv5r.py
@@ -587,7 +587,10 @@ def _do_download(radio):
         data += _read_block(radio, i, 0x40, False)
 
     if append_model:
-        data += radio.MODEL.ljust(8)
+        data += radio.MODEL.ljust(8).encode()
```

i have a merge request : [https://github.com/atpage/chirp/pull/4](https://github.com/atpage/chirp/pull/4)

**Comment by atpage** [comment]
Thanks, I merged this and the other PR for Issue #6, and will submit them upstream as well.
